### ISSUE TITLE
rhythm

### ISSUE THREAD

**Issue by flckv** [NVIDIA/RAD-MMM#9]
Great work, thank you for sharing.
Did you include rhythm in the training process? May you clarify your [ symbol tool ](https://github.com/NVIDIA/RAD-MMM/blob/adc9ad93a4036614b7899e38801a2ff84d464a4a/tts_text_processing/symbols.py#L57) for rhythm, please? 

`'rhythm': ['.', '◌‿◌'],`

**Comment by rohanbadlani** [comment]
we use segregated token list i.e markers and phonemes are treated separate tokens (and have different token ids)...phonemized text can have rhythm markers (eg: https://github.com/espeak-ng/espeak-ng/blob/master/docs/phonemes.md#suprasegmentals)
